import json
import pytest
from django.forms.models import model_to_dict

from .factories import BookFactory

pytestmark = pytest.mark.django_db


class TestBookEndpoint:
    endpoint = '/books/'

    def test_list(self, api_client):
        # Fills data in Book table for testing
        books_example = BookFactory.create_batch(6)
        # I'm converting one of the generated models to dict for further check
        book_to_check = model_to_dict(books_example[0])
        book_to_check['price'] = str(book_to_check['price'])

        response = api_client().get(self.endpoint)

        assert response.status_code == 200
        # Test if book generated by factory is in response json
        assert book_to_check in json.loads(response.content)
